/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    '副本': typeof import('./../components/Svg/new_file - 副本.vue')['default']
    AuditReport: typeof import('./../components/Index/auditReport.vue')['default']
    Auth: typeof import('./../components/Index/auth.vue')['default']
    Booster: typeof import('./../components/Booster/index.vue')['default']
    BoosterItem: typeof import('./../components/Booster/BoosterItem.vue')['default']
    Chart: typeof import('./../components/Chart/index.vue')['default']
    Close: typeof import('./../components/Svg/close.vue')['default']
    Eventer: typeof import('./../components/Eventer/index.vue')['default']
    GhostButton: typeof import('./../components/GhostButton.vue')['default']
    HeaderBar: typeof import('./../components/HeaderBar.vue')['default']
    HelpCenter: typeof import('./../components/Index/helpCenter.vue')['default']
    IndexTabs: typeof import('./../components/Index/indexTabs.vue')['default']
    Mining: typeof import('./../components/Index/mining.vue')['default']
    MinintForm: typeof import('./../components/Index/minintForm.vue')['default']
    NavBar: typeof import('./../components/NavBar.vue')['default']
    New_file: typeof import('./../components/new_file.vue')['default']
    'New_file - 副本': typeof import('./../components/Svg/new_file - 副本.vue')['default']
    Partner: typeof import('./../components/Index/partner.vue')['default']
    Qa: typeof import('./../components/Index/Qa.vue')['default']
    RewardItem: typeof import('./../components/RewardList/RewardItem.vue')['default']
    RewardList: typeof import('./../components/RewardList/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Service: typeof import('./../components/Svg/service.vue')['default']
    ServiceBtn: typeof import('./../components/Svg/serviceBtn.vue')['default']
    Servicer: typeof import('./../components/Servicer.vue')['default']
    TabBar: typeof import('./../components/TabBar.vue')['default']
    VanCollapse: typeof import('vant/es')['Collapse']
    VanCollapseItem: typeof import('vant/es')['CollapseItem']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanCountDown: typeof import('vant/es')['CountDown']
    VanIcon: typeof import('vant/es')['Icon']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopover: typeof import('vant/es')['Popover']
    VanPopup: typeof import('vant/es')['Popup']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
    WalletConnect: typeof import('./../components/WalletConnect/index.vue')['default']
    WalletSup: typeof import('./../components/WalletSup.vue')['default']
  }
}
