/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '404': RouteRecordInfo<'404', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/account/': RouteRecordInfo<'/account/', '/account', Record<never, never>, Record<never, never>>,
    '/account/components/charge': RouteRecordInfo<'/account/components/charge', '/account/components/charge', Record<never, never>, Record<never, never>>,
    '/account/components/eventerInfo': RouteRecordInfo<'/account/components/eventerInfo', '/account/components/eventerInfo', Record<never, never>, Record<never, never>>,
    '/account/components/indexTabs': RouteRecordInfo<'/account/components/indexTabs', '/account/components/indexTabs', Record<never, never>, Record<never, never>>,
    '/account/components/myAccount': RouteRecordInfo<'/account/components/myAccount', '/account/components/myAccount', Record<never, never>, Record<never, never>>,
    '/account/components/withdraw': RouteRecordInfo<'/account/components/withdraw', '/account/components/withdraw', Record<never, never>, Record<never, never>>,
    '/account/new_file': RouteRecordInfo<'/account/new_file', '/account/new_file', Record<never, never>, Record<never, never>>,
    'charts': RouteRecordInfo<'charts', '/charts', Record<never, never>, Record<never, never>>,
    'counter': RouteRecordInfo<'counter', '/counter', Record<never, never>, Record<never, never>>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'KeepAlive': RouteRecordInfo<'KeepAlive', '/keepalive', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'mock': RouteRecordInfo<'mock', '/mock', Record<never, never>, Record<never, never>>,
    'profile': RouteRecordInfo<'profile', '/profile', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'settings': RouteRecordInfo<'settings', '/settings', Record<never, never>, Record<never, never>>,
    '/test/new_file': RouteRecordInfo<'/test/new_file', '/test/new_file', Record<never, never>, Record<never, never>>,
    '/test/temp2': RouteRecordInfo<'/test/temp2', '/test/temp2', Record<never, never>, Record<never, never>>,
    'unocss': RouteRecordInfo<'unocss', '/unocss', Record<never, never>, Record<never, never>>,
  }
}
