/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '404': RouteRecordInfo<'404', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/account/': RouteRecordInfo<'/account/', '/account', Record<never, never>, Record<never, never>>,
    '/account/components/charge': RouteRecordInfo<'/account/components/charge', '/account/components/charge', Record<never, never>, Record<never, never>>,
    '/account/components/eventerInfo': RouteRecordInfo<'/account/components/eventerInfo', '/account/components/eventerInfo', Record<never, never>, Record<never, never>>,
    '/account/components/indexTabs': RouteRecordInfo<'/account/components/indexTabs', '/account/components/indexTabs', Record<never, never>, Record<never, never>>,
    '/account/components/myAccount': RouteRecordInfo<'/account/components/myAccount', '/account/components/myAccount', Record<never, never>, Record<never, never>>,
    '/account/components/myBoosterComponents': RouteRecordInfo<'/account/components/myBoosterComponents', '/account/components/myBoosterComponents', Record<never, never>, Record<never, never>>,
    '/account/components/myEvent': RouteRecordInfo<'/account/components/myEvent', '/account/components/myEvent', Record<never, never>, Record<never, never>>,
    '/account/components/withdraw': RouteRecordInfo<'/account/components/withdraw', '/account/components/withdraw', Record<never, never>, Record<never, never>>,
    '/account/new_file': RouteRecordInfo<'/account/new_file', '/account/new_file', Record<never, never>, Record<never, never>>,
    '/records/': RouteRecordInfo<'/records/', '/records', Record<never, never>, Record<never, never>>,
    '/records/components/profitRecord': RouteRecordInfo<'/records/components/profitRecord', '/records/components/profitRecord', Record<never, never>, Record<never, never>>,
    '/records/components/withdrawRecord': RouteRecordInfo<'/records/components/withdrawRecord', '/records/components/withdrawRecord', Record<never, never>, Record<never, never>>,
    '/test/new_file': RouteRecordInfo<'/test/new_file', '/test/new_file', Record<never, never>, Record<never, never>>,
    '/test/temp2': RouteRecordInfo<'/test/temp2', '/test/temp2', Record<never, never>, Record<never, never>>,
    'unocss': RouteRecordInfo<'unocss', '/unocss', Record<never, never>, Record<never, never>>,
  }
}
