<template>
  <div class="server_wrap gborder" v-if="stateStore.loginStatus">
    <div class="pad_4">
      <template v-if="type == 'list'">
        <div class="server_list" v-show="showList">
          <div class="server_btn gbg br_50 mb_10" @click="openHref(customerService)">
            <service class="gcolor"></service>
          </div>
        </div>
        <div class="server_btn br_50" @click="showList = !showList">
          <serviceBtn class="gcolor" v-if="!showList"></serviceBtn>
          <close class="gcolor" v-else></close>
        </div>
      </template>
      <template v-if="type == 'sigle'">
        <div class="server_btn br_50" @click="openHref(customerService)">
          <serviceBtn class="gcolor"></serviceBtn></div
      ></template>
    </div>
    <i class="border_line border_scroll" style="border-radius: 0.7rem"></i>
  </div>
</template>

<script setup lang="ts">
const { t } = useI18n();
import close from '@/components/Svg/close.vue';
import serviceBtn from '@/components/Svg/serviceBtn.vue';
import service from '@/components/Svg/service.vue';
import { CustomerService } from '@/api/api';
import { useStateStore } from '@/stores/state';
const stateStore = useStateStore();
const showList = ref(false);
const customerService = ref('');
let type = ref('');
type.value = window['serviceType'];
function openHref() {
  if (stateStore.servieLink) {
    CustomerService().then((res) => {
      window.open(res.data);
      showList.value = false;
    });
  } else {
    window.open(stateStore.servieLink);
  }
  // window.open(v);
  // showList.value = false;
}
function fetchCustomerService() {
  CustomerService().then((res) => {
    customerService.value = res.data;
  });
}
watch(
  () => stateStore.loginStatus,
  (newMode) => {
    if (newMode) {
    }
  }
);
onMounted(() => {
  if (stateStore.loginStatus) {
    stateStore.fetchServieLink();
  }
});
</script>

<style scoped>
.server_wrap {
  /* width: 12vw; */
  /* height: 12vw; */
  border-radius: 7vw;
  position: fixed;
  right: 5vw;
  bottom: 15vh;
}
.server_btn {
  width: 10vw;
  height: 10vw;
  /* margin: calc(var(--base) * 14); */
}
/* ----------------------------------------------
* Generated by Gradienty on 2024-12-11 07:34
* animation slide-top-normal
* ----------------------------------------
*/
@keyframes slide-top-normal {
  0% {
    transform: translateY(0);
  }
  100% {
    transform: translateY(-100px);
  }
}

.slide-top-normal {
  animation: slide-top-normal 1s ease-in 0s 1 normal none;
}
</style>
